{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mychart.serviceAccountName" . }}-podctrl
subjects:
- kind: ServiceAccount
  name: {{ include "mychart.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "mychart.fullname" . }}-podctrl
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mychart.fullname" . }}-podctrl
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["telegrafd"]
  verbs: ["get", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["get", "patch"]
{{- end }}
